# Generated by Django 5.1.1 on 2024-10-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_childaccount_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
