# Generated by Django 5.1.1 on 2024-10-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
