# Generated by Django 5.1.1 on 2024-10-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_booking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childaccount',
            name='learning_areas',
            field=models.CharField(choices=[('math', 'Mathematics')], max_length=100),
        ),
    ]
