# Generated by Django 5.1.1 on 2024-10-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_booking_date_booking_duration_booking_other_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='topic',
            field=models.CharField(blank=True, choices=[('addition', 'Addition'), ('subtraction', 'Subtraction'), ('multiplication', 'Multiplication'), ('division', 'Division'), ('fractions', 'Fractions'), ('decimals', 'Decimals'), ('geometry', 'Geometry'), ('algebra', 'Algebra'), ('word_problems', 'Word Problems'), ('other', 'Other (please specify)')], max_length=200, null=True),
        ),
    ]
