# Generated by Django 5.1.1 on 2024-10-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_alter_booking_duration_alter_booking_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isApproved',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
