# Generated by Django 5.1.1 on 2024-10-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_booking_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
